#!/usr/bin/env bash

if tmux list-windows | grep -q "tests"; then
    tmux select-window -t tests
else
    tmux neww -n tests && tmux select-window -t tests
fi

tmux send-keys -t tests 'go test ./...' Enter
